# This is a basic workflow to help you get started with Actions

name: Run Lint Checks

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run_lint_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Detekt & Ktlint
        run: ./gradlew ktlintCheck detekt --continue || true

      - name: Check HTML Report
        run: ls -l app/build/reports/detekt/

      - name: Upload Detekt HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: detekt-html-report
          path: app/build/reports/detekt/detekt.html