name: Run Lint Checks

on:
  push:
    branches: [ "feature/add-pmd-to-github-action" ]

jobs:
  run_lint_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run PMD for all variants
        run: |
          ./gradlew runPmdFreeDebug --continue || true
          ./gradlew runPmdFreeRelease --continue || true
          ./gradlew runPmdPaidDebug --continue || true
          ./gradlew runPmdPaidRelease --continue || true

      - name: Show all PMD report files
        run: find . -name "pmd.*"

      - name: List PMD report directory
        run: ls -la app/build/reports/pmd/

      - name: Upload PMD Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-reports
          path: |
            app/build/reports/pmd/freeDebug/
            app/build/reports/pmd/freeRelease/
            app/build/reports/pmd/paidDebug/
            app/build/reports/pmd/paidRelease/
