name: Run Lint Checks

on:
  push:
    branches: [ "feature/add-pmd-to-github-action" ]

jobs:
  run_lint_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run PMD
        run: ./gradlew runPmd

      - name: Show all PMD files
        run: find . -name "pmd.*"

      - name: List PMD report directory
        run: ls -la build/reports/pmd/

      - name: Upload PMD Report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd/